mail:
  send_mail: 284029574@qq.com
  mail_code: cnsxgpzngwqnbhfe
  receive_mail:
  - 741148263@qq.com
  - 3228373734@qq.com
  cc:
    - 642282610@qq.com


url:
#    test_url: http://62.234.58.195:8082/
    test_url: https://www.baidu.com



